apiVersion: v1
kind: Service
metadata:
  name: kube
spec:
  selector:
    app: kube
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31100
