apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
  labels:
    app: kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube
        image: dasariumamahesh/node-crypto:0.0.1
        ports:
        - containerPort: 3000
